site_name: Terminal Game Platform

nav:
    - Home: index.md

theme: bootstrap386

repo_url: https://github.com/terminal-game-platform/launcher

site_description: This is the documentation site for project_name.

site_author: Kieran Wood
